const TAGLINES = [
  "No matter the universe... they’re probably in the wrong job.",
  "Heroes, villains, and everyone in between... poorly assigned.",
  "Saving worlds was easier than this.",
  "Assembling the worst possible workforce.",
  "Elite talent. Questionable decisions.",
  "Great power. Terrible placement.",
  "They deserve better. They won’t get it.",
  "Somewhere else, they’re doing great.",
  "From every universe... into the wrong jobs.",
  "Every universe is hiring. You’re in charge.",
  "Across the multiverse... HR has failed.",
  "Infinite universes. Same bad management.",
  "Multiversal talent, local mismanagement.",
  "Bringing together the least compatible team imaginable.",
  "Draw your crew. Regret your choices.",
  "Every hand tells a worse story.",
  "Pulled from the deck... straight into chaos.",
  "You drew them. Now deal with them.",
  "Luck got them here. You decide their fate.",
  "HR approved none of this.",
  "Performance reviews will be awkward.",
  "Morale is a suggestion.",
  "Retention is not guaranteed.",
  "This is why we can’t keep good people.",
  "Now hiring: literally anyone.",
  "Training not provided.",
  "Management decisions were made.",
  "This seemed like a good idea at the time.",
  "What could possibly go wrong?",
  "It gets worse the more you think about it.",
  "We regret nothing. Probably.",
  "It worked in another universe.",
  "With great power comes great mismanagement.",
  "I find your lack of staffing... disturbing.",
  "These aren’t the employees you’re looking for.",
  "I have a bad feeling about this workforce.",
  "To boldly assign where no one should go.",
  "You either quit a hero... or get reassigned long enough to become the problem.",
  "Why so serious? It’s just terrible management.",
  "I am inevitable... and so are bad assignments.",
  "Winter is coming. So are performance reviews.",
  "Not all those who wander are... correctly assigned.",
  "One does not simply manage this workforce.",
  "The needs of the many outweigh... proper job placement.",
  "That’s no moon. That’s a staffing issue.",
  "I’ll be back... for reassignment.",
  "Houston, we have a management problem.",
  "You can’t handle the workforce!",
  "Say hello to my little staffing problem.",
  "Here’s looking at you, poor decisions.",
  "You had me at terrible management.",
  "Keep your friends close... and your employees confused.",
  "We’re gonna need a bigger HR department.",
  "It’s alive... and badly assigned.",
  "I see dead morale.",
  "This is how it starts... with one bad assignment.",
  "The chaos is strong with this one."
];