// ==========================================================
// Character Tags
// ----------------------------------------------------------
// Tags describe what a character IS, DOES, or tends to prefer.
// Used for filtering, compatibility, bonuses, conflicts,
// and future favorite/disliked systems.
// ==========================================================

const CHARACTER_TAGS = {
  // ========================================================
  // Species / Being Types
  // ========================================================

  HUMAN: "human",
  ROBOT: "robot",
  ANDROID: "android",
  CYBORG: "cyborg",
  AI: "ai",
  ALIEN_UNKNOWN: "alien_unknown",
  ANIMAL: "animal",

  // Star Wars / Sci-Fi Species
  WOOKIEE: "wookiee",
  EWOK: "ewok",
  TWILEK: "twilek",
  ZABRAK: "zabrak",
  KAMINOAN: "kaminoan",
  TUSKEN: "tusken",
  GUNGAN: "gungan",
  GAMORREAN: "gamorrean",
  JAWA: "jawa",

  // MCU / Avatar
  KREE: "kree",
  SKRULL: "skrull",
  NA_VI: "na_vi",

  // Star Trek
  KLINGON: "klingon",
  ROMULAN: "romulan",
  VULCAN: "vulcan",
  BORG: "borg",

  // Fantasy
  ELF: "elf",
  DWARF: "dwarf",
  HOBBIT: "hobbit",
  ORC: "orc",
  GOBLIN: "goblin",
  TROLL: "troll",
  ENT: "ent",
  DRAGON: "dragon",

  // Supernatural
  VAMPIRE: "vampire",
  WEREWOLF: "werewolf",
  DEMON: "demon",
  ANGEL: "angel",
  GHOST: "ghost",
  SPIRIT: "spirit",
  ZOMBIE: "zombie",
MONSTER: "monster",
CREATURE: "creature",

  // Comic / Enhanced
  MUTANT: "mutant",
  SUPERHUMAN: "superhuman",
  KRYPTONIAN: "kryptonian",
  INHUMAN: "inhuman",
  ASGARDIAN: "asgardian",

  // ========================================================
  // Skills / Professions
  // ========================================================

  SCIENTIST: "scientist",
  ENGINEER: "engineer",
  DOCTOR: "doctor",
  TEACHER: "teacher",
  STUDENT: "student",
  MANAGER: "manager",
  SALESPERSON: "salesperson",
  OFFICE_WORKER: "office_worker",
  PILOT: "pilot",
  DRIVER: "driver",
  CHEF: "chef",
  BARTENDER: "bartender",
  PERFORMER: "performer",
  JOURNALIST: "journalist",
  DETECTIVE: "detective",
  SPY: "spy",
  SOLDIER: "soldier",
  GUARD: "guard",
  WARRIOR: "warrior",
  HACKER: "hacker",
  MECHANIC: "mechanic",
  SCAVENGER: "scavenger",
  ROYALTY: "royalty",
  MUSICIAN: "musician",
  SERVANT: "servant",
  POLITICIAN: "politician",
  AGENT: "agent",
  GAMER: "gamer",

  // ========================================================
  // Personality / Behavior
  // ========================================================

  BRAVE: "brave",
  LOYAL: "loyal",
  CHAOTIC: "chaotic",
  LAZY: "lazy",
  ANXIOUS: "anxious",
  GREEDY: "greedy",
  ARROGANT: "arrogant",
  CHARISMATIC: "charismatic",
  CURIOUS: "curious",
  DISCIPLINED: "disciplined",
  MISCHIEVOUS: "mischievous",
  HOTHEADED: "hotheaded",
GOOFY: "goofy",
LEADER: "leader",
ELDERLY: "elderly",
CUTE: "cute",
ATHLETE: "athlete",
CONFIDENT: "confident",
BUREAUCRAT: "bureaucrat",
NEWSCASTER: "newscaster",
LAWYER: "lawyer",
JUDGE: "judge",
INDULGENT: "indulgent",
SALESMAN: "salesman",
INVENTOR: "inventor",
HOLIDAY: "holiday",
FAMILY: "family",
HUSTLER: "hustler",
DIPLOMAT: "diplomat",
DANGEROUS: "dangerous",
WISE: "wise",
CHILD: "child",
KIND: "kind",
AWKWARD: "awkward",
POPULAR: "popular",
BULLY: "bully",
COWARDLY: "cowardly",
  DROID: "droid",
  JEDI: "jedi",
  SMUGGLER: "smuggler",
  PRINCESS: "princess",
  TRANSLATOR: "translator",
  FROZEN: "frozen",
  ICONIC: "iconic",
  FORCE_GHOST: "force_ghost",
  MENTOR: "mentor",
  RESILIENT: "resilient",

  // ========================================================
  // Alignment / Social Role
  // ========================================================

  REBEL: "rebel",
  VILLAIN: "villain",
  LAWFUL: "lawful",
  CRIMINAL: "criminal",
  MILITARY: "military",
  NOBLE: "noble",
  OUTCAST: "outcast",
  SHADY: "shady",
  SURVIVOR: "survivor",

  // ========================================================
  // Environment / Comfort
  // ========================================================

FLYING: "flying",
GROSS: "gross",
  DESERT: "desert",
  COLD: "cold",
  SPACE: "space",
  SEA: "sea",
  MAGICAL: "magical",
  SUPERNATURAL: "supernatural",
  URBAN: "urban",
  RURAL: "rural"

};


const CHARACTER_TAG_DEFS = {
  // Species / Being Types
  human: { label: "#human", description: "Ordinary human being" },
  robot: { label: "#robot", description: "Mechanical artificial being" },
  android: { label: "#android", description: "Humanlike artificial being" },
  cyborg: { label: "#cyborg", description: "Part organic machine" },
  ai: { label: "#ai", description: "Artificial intelligence" },
  alien_unknown: { label: "#alien", description: "Unknown alien species" },
  animal: { label: "#animal", description: "Non-human creature" },

  wookiee: { label: "#wookiee", description: "Strong loyal species" },
  ewok: { label: "#ewok", description: "Small tribal species" },
  twilek: { label: "#twilek", description: "Charismatic alien species" },
  zabrak: { label: "#zabrak", description: "Hardy horned species" },
  kaminoan: { label: "#kaminoan", description: "Elegant cloning experts" },
tusken: { label: "#tusken", description: "Desert survivor culture" },
gungan: { label: "#gungan", description: "Amphibious Naboo species" },
gamorrean: { label: "#gamorrean", description: "Strong porcine species" },
jawa: { label: "#jawa", description: "Small desert scavenger" },

  kree: { label: "#kree", description: "Militaristic alien empire" },
  skrull: { label: "#skrull", description: "Shapeshifting alien species" },
  na_vi: { label: "#na'vi", description: "Nature-connected species" },

  klingon: { label: "#klingon", description: "Warrior honor culture" },
  romulan: { label: "#romulan", description: "Strategic secretive species" },
  vulcan: { label: "#vulcan", description: "Logical disciplined beings" },
  borg: { label: "#borg", description: "Assimilating collective species" },

  elf: { label: "#elf", description: "Graceful long-lived being" },
  dwarf: { label: "#dwarf", description: "Stout underground folk" },
  hobbit: { label: "#hobbit", description: "Small comfort-loving folk" },
  orc: { label: "#orc", description: "Rough aggressive species" },
  goblin: { label: "#goblin", description: "Cunning troublesome species" },
  troll: { label: "#troll", description: "Large brutal creature" },
  ent: { label: "#ent", description: "Ancient tree shepherd" },
  dragon: { label: "#dragon", description: "Powerful legendary creature" },

  vampire: { label: "#vampire", description: "Undead night creature" },
  werewolf: { label: "#werewolf", description: "Moon-cursed shapeshifter" },
  demon: { label: "#demon", description: "Supernatural hostile being" },
  angel: { label: "#angel", description: "Celestial supernatural being" },
  ghost: { label: "#ghost", description: "Lingering dead spirit" },
  spirit: { label: "#spirit", description: "Nonphysical supernatural being" },
  zombie: { label: "#zombie", description: "Reanimated dead being" },
monster: { label: "#monster", description: "Hostile unnatural being" },
creature: { label: "#creature", description: "Non-human beast" },

  mutant: { label: "#mutant", description: "Genetically altered human" },
  superhuman: { label: "#superhuman", description: "Beyond normal human" },
  kryptonian: { label: "#kryptonian", description: "Superpowered alien" },
  inhuman: { label: "#inhuman", description: "Terrigen-altered lineage" },
  asgardian: { label: "#asgardian", description: "Mythic alien godlike being" },

  // Skills / Professions
  scientist: { label: "#scientist", description: "Science-focused worker" },
  engineer: { label: "#engineer", description: "Builds and fixes systems" },
  doctor: { label: "#doctor", description: "Medical care provider" },
  teacher: { label: "#teacher", description: "Educates and guides others" },
  student: { label: "#student", description: "Learns and develops skills" },
  manager: { label: "#manager", description: "Coordinates other workers" },
  salesperson: { label: "#salesperson", description: "Sells to customers" },
  office_worker: { label: "#office_worker", description: "Handles office tasks" },
  pilot: { label: "#pilot", description: "Operates flying vehicles" },
  driver: { label: "#driver", description: "Operates ground vehicles" },
  chef: { label: "#chef", description: "Prepares food professionally" },
  bartender: { label: "#bartender", description: "Serves drinks socially" },
  performer: { label: "#performer", description: "Entertains an audience" },
  journalist: { label: "#journalist", description: "Reports public information" },
  detective: { label: "#detective", description: "Investigates hidden facts" },
  spy: { label: "#spy", description: "Handles secret missions" },
  soldier: { label: "#soldier", description: "Trained military combatant" },
  guard: { label: "#guard", description: "Protects people or places" },
  warrior: { label: "#warrior", description: "Combat-focused fighter" },
  hacker: { label: "#hacker", description: "Exploits digital systems" },
  mechanic: { label: "#mechanic", description: "Repairs machines and vehicles" },
  scavenger: { label: "#scavenger", description: "Finds value in junk" },
  royalty: { label: "#royalty", description: "Born to status" },
  musician: { label: "#musician", description: "Performs music professionally" },
  servant: { label: "#servant", description: "Serves powerful people" },
  politician: { label: "#politician", description: "Navigates political systems" },
agent: { label: "#agent", description: "Government field operative" },
gamer: { label: "#gamer", description: "Plays games seriously" },

  // Personality / Behavior
  brave: { label: "#brave", description: "Faces danger willingly" },
  loyal: { label: "#loyal", description: "Sticks with allies" },
  chaotic: { label: "#chaotic", description: "Creates unpredictable outcomes" },
  lazy: { label: "#lazy", description: "Avoids unnecessary work" },
  anxious: { label: "#anxious", description: "Stresses under pressure" },
  greedy: { label: "#greedy", description: "Motivated by rewards" },
  arrogant: { label: "#arrogant", description: "Overestimates own importance" },
  charismatic: { label: "#charismatic", description: "Influences people easily" },
  curious: { label: "#curious", description: "Seeks new discoveries" },
  disciplined: { label: "#disciplined", description: "Follows structure well" },
  mischievous: { label: "#mischievous", description: "Causes playful trouble" },
  hotheaded: { label: "#hotheaded", description: "Acts before thinking" },
goofy: { label: "#goofy", description: "Silly but useful" },
leader: { label: "#leader", description: "Guides other workers" },
elderly: { label: "#elderly", description: "Older experienced character" },
cute: { label: "#cute", description: "Disarmingly adorable" },
athlete: { label: "#athlete", description: "Physically competitive" },
confident: { label: "#confident", description: "Believes in themselves" },
bureaucrat: { label: "#bureaucrat", description: "Loves rules and forms" },
newscaster: { label: "#newscaster", description: "Broadcasts public information" },
lawyer: { label: "#lawyer", description: "Argues professionally" },
judge: { label: "#judge", description: "Legal decision maker" },
indulgent: { label: "#indulgent", description: "Loves comfort and luxury" },
salesman: { label: "#salesman", description: "Sells aggressively" },
inventor: { label: "#inventor", description: "Creates new devices" },
holiday: { label: "#holiday", description: "Seasonal special character" },
family: { label: "#family", description: "Family connection matters" },
hustler: { label: "#hustler", description: "Always chasing profit" },
diplomat: { label: "#diplomat", description: "Handles negotiations" },
dangerous: { label: "#dangerous", description: "Personally hazardous" },
musician: { label: "#musician", description: "Performs music professionally" },
servant: { label: "#servant", description: "Serves powerful people" },
politician: { label: "#politician", description: "Navigates political systems" },
wise: { label: "#wise", description: "Experienced and insightful" },
child: { label: "#child", description: "Not fully matured" },
kind: { label: "#kind", description: "Helpful and caring" },
awkward: { label: "#awkward", description: "Socially uncomfortable" },
popular: { label: "#popular", description: "High social status" },
bully: { label: "#bully", description: "Intimidates weaker people" },
cowardly: { label: "#cowardly", description: "Avoids real danger" },

  // Alignment / Social Role
  rebel: { label: "#rebel", description: "Opposes authority" },
  villain: { label: "#villain", description: "Morally questionable actor" },
  lawful: { label: "#lawful", description: "Respects rules and order" },
  criminal: { label: "#criminal", description: "Comfortable breaking laws" },
  military: { label: "#military", description: "Military-affiliated character" },
  noble: { label: "#noble", description: "High-status background" },
  outcast: { label: "#outcast", description: "Does not fit society" },
shady: { label: "#shady", description: "Questionable reputation" },
survivor: { label: "#survivor", description: "Endured serious hardship" },

  droid: { label: "#droid", description: "Sentient mechanical being" },
  jedi: { label: "#jedi", description: "Force-trained guardian" },
  smuggler: { label: "#smuggler", description: "Unlicensed cargo expert" },
  princess: { label: "#princess", description: "Royal political figure" },
  translator: { label: "#translator", description: "Bridges language gaps" },
  frozen: { label: "#frozen", description: "Temporarily immobilized" },
  iconic: { label: "#iconic", description: "Legendary memorable form" },
  force_ghost: { label: "#force_ghost", description: "Ascended Force spirit" },
  mentor: { label: "#mentor", description: "Guides others forward" },
  resilient: { label: "#resilient", description: "Endures serious hardship" },

  // Environment / Comfort
flying: { label: "#flying", description: "Comfortable in the air" },
gross: { label: "#gross", description: "Physically unpleasant" },
  desert: { label: "#desert", description: "Handles arid environments" },
  cold: { label: "#cold", description: "Handles cold environments" },
  space: { label: "#space", description: "Comfortable beyond planets" },
  sea: { label: "#sea", description: "Comfortable around water" },
  magical: { label: "#magical", description: "Connected to magic" },
  supernatural: { label: "#supernatural", description: "Beyond natural explanation" },
  urban: { label: "#urban", description: "Comfortable in cities" },
  rural: { label: "#rural", description: "Comfortable in countryside" }
};